test:
	suppressor pass 'RESULT=pass babel-node --presets=es2015 test.js'
	suppressor fail 'RESULT=fail1 babel-node --presets=es2015 test.js'
	suppressor fail 'RESULT=fail2 babel-node --presets=es2015 test.js'
	suppressor fail 'RESULT=fail3 babel-node --presets=es2015 test.js'
	suppressor fail 'RESULT=fail4 babel-node --presets=es2015 test.js'
	suppressor fail 'RESULT=fail5 babel-node --presets=es2015 test.js'
